### ISSUE TITLE
Feature Request: Add support for mpd's built-in http streaming.

### ISSUE THREAD

**Issue by klundry** [gateship-one/malp#14]
It would be great to be able to utilize the http streaming function of mpd.

**Comment by 1xPdd** [comment]
I would certainly love to see this feature added.

Just to add an fyi. I know Mpdroid had a bit of trouble getting this to work properly and never seemed to iron out all the bugs, somehow because of how Android handles audio (at least that's what I read on their github, I think). If you were looking to borrow code or inspiration, however, both VLC and ServeStream (on Fdroid) had no problem streaming from MPD if they were pointed to the stream. Which is to say, it is possible to coax Android to play nice with MPD.

**Comment by djselbeck** [comment]
The code for MALP is almost done. There is only some small code left (Audiofocus request).

After this I will release this feature as experimental. If there are bugs left I'll try to fix them as good as possible.

But I will most certainly not include the player code of vlc or else because 1. they don't use the Android MediaPlayer framework and 2. this is a MPD client and not a streaming client so the priority is on the MPD control side.

As I have absolutely no need for this feature I'll try to implement it as good as possible for me but thats it ;).

**Comment by 1xPdd** [comment]
Thanks for you reply. No worries--I understand not wanting to add a feature you don't use or need. I just hadn't seen a roadmap. Thanks, though, for the great app.

**Comment by klundry** [comment]
Thank you.  I use MALP all the time and it's great. Can't wait to see what you come up with for the http streaming.  Currently, it is possible to control mpd with malp and then open up a browser and go to your mpd streaming url to listen to it.  It's not very elegant but it works.  Being built into malp would be much nicer.  I'll get on the testing of it as soon as it's ready.

**Comment by djselbeck** [comment]
Version with this enabled is released to google and taged here. So a F-Droid release should follow.

I did NOT test this feature very much, so it is released as experimental

**Comment by 1xPdd** [comment]
Hey, I just noticed F-droid has the new version with streaming support. I flicked the switch to start streaming--and it worked, more or less without a hitch. That quite made my day! Thanks.

A few minor things I've noticed so far:

* When stop is pressed, streaming doesn't seem to stop immediately. Not sure if it's waiting from something from mpd.
* If I stop an album, then start playing again, it plays but streaming has also been stopped (i.e., I have to select 'Start streaming' again).
* The volume slider appears as if muted and when I try to change the volume, it changes back to a muted state after a moment. It does however, stream with sound, which is changeable via Android.

Fyi, for anyone else trying this, I'm using as stream with the lame encoder at 320. I tried Vorbis but it pegged the cpu of my pi. Flac probably works with less cpu but I have shitty internet, so...

Anyhow, just wanted to say thanks!!

**Comment by djselbeck** [comment]
Thanks for your feedback. I will check on these problems. As I said, I did not really test it much, so any productive feedback is absolutely welcome 👍

**Comment by klundry** [comment]
I briefly tried this as well, though not long enough find the issues 1xPdd found :). I will try to to test it a little this week and chime in if I find anything.  

Thanks again for this feature.  Love it!

**Comment by rubyconn** [comment]
Wow, this feature is great! I've been looking for an app I can use to easily stream and control music from mpd, and this nearly ticks all the boxes.

One think I'd love to see is an option in the settings that lets you choose whether it should always start streaming whenever you start playback. This way it will function like any other output, and you won't have to select "Start streaming" everytime you start playing after pausing.

**Comment by mazze13** [comment]
Hi,

Thanks for this great FOSS app, I tried different mpd clients for Android, and this is hands-down the best for me. Because we don't use tags extensively (self-recorded stuff) I especially appreciate the possibility to walk through the file tree.

Sometimes we'd like to stream the sound of a spontaneously selected youtube entry from the phone to the mpd box. I have M. A. L. P. 1.1.8 from F-droid, but the menu entry "Start streaming" is missing.

Is there any mpd configuration prerequisite for this to even show up?

Thank you again for the great work, and have a nice day!

mazze13

**Comment by mazze13** [comment]
Hi,

As I did not get any response yet, I'd like to ask back: Did I miss something obvious rendering my question unnecessary?

Thanks for any hint,

mazze13

**Comment by klundry** [comment]
@mazze13 That is not a capability provided by mpd. You might be slightly misunderstanding what mpd is meant to do. The streaming feature being discussed here is streaming music from the mpd server to your client(phone). 

Maybe check out mopidy. It might do something more like what you're looking for.

**Comment by mazze13** [comment]
@klundry Thank you for the clarification, I now figured out that I understood 'streaming' here the wrong way.

My perception what MPD is meant to do was that the server should output audio through its audio hardware, and I saw that he can play not only files but also _from_ network/streaming sources.

However, I did not find any APP for Android that would do streaming e. g. Youtube-Playback from the phone to somewhere else, and I also did not find that in Mopidy. If it's really there it would be great if you could point that out to me.

Anyway, we're liking M.A.L.P. a lot, thanks for the goot work!

**Comment by djselbeck** [comment]
Closing this. Remaining issues should be opened as separate issues, please
