### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [gateship-one/malp#19]
When I perform this sequence of events, the dialog on screen disappears:

Sequence 1:
1. Open Side Drawer
2. Click on App Settings
3. Click on Artwork Settings
4. Click on Try to load all images for your database*
5. Orientation Change

**Comment by djselbeck** [comment]
Hello,

as a fellow computer science researcher I have some problems with your way of going on rampage on github. Although I think that automatic testing of applications is a good thing the way you open the issues most certainly is not. 

Instead of opening a large number of issues with misleading text (for example this one) you should maybe proceed in another way like contacting the authors first, to ask if they are interested at all or if they want to handle it on their own. 

Another thing I would like to see is an automatic patch for those repeating issues. This would be an research challenge I guess instead of repeatedly testing the same (boring) use cases.

As I am interested in increasing the quality of this software I will fix the issues in time but at a low priority because of more important things that needs attention.
Greetings

Hendrik Borghorst

P.S.: It would be great to have an email address to contact you or your research team linked in github.
P.P.S.: This issue is invalid because there is not even a dialog with the above sequence.

**Comment by reverse-unina** [comment]
Hello,

You can contact me at this email address: reverse.unina@gmail.com.

I edited the event sequence since the preference reported at step 4 was wrong.

Thank you
