### ISSUE TITLE
Add "save" button when creating profile for more clarity

### ISSUE THREAD

**Issue by mueller-ma** [gateship-one/malp#23]
Hi,
when I created my first profile I needed some time to realize that the new profile will be saved automaticly when going back. In my opinion this behavior is very unexpected. I expect that the "back" arrow will discard all changes

**Comment by djselbeck** [comment]
Hi,

this behaviour is consistent with other settings in Android. I already thought about it before with a colleague. But if you for example check the APN settings on android you can create a new APN and there is also no save button because it is unnatural to the android design guidelines. 

However there is a discard button. I may think about that button.
